/*! Auto-generated. This file was generated by Nca.Valdr. */
(function() {
    "use strict";
    angular
        .module("app")
        .config(config);
    config.$inject = ["valdrProvider"];
    function config(valdrProvider) {
        valdrProvider.addConstraints({
  "address": {
    "city": {
      "required": {
        "message": "City is required."
      }
    },
    "zipCode": {
      "required": {
        "message": "Zip code is required."
      },
      "size": {
        "min": 4,
        "max": 6,
        "message": "Zip code must be between 4 and 6 characters."
      }
    }
  },
  "person": {
    "firstName": {
      "required": {
        "message": "First name is required."
      },
      "size": {
        "min": 1,
        "max": 30,
        "message": "First name must be between 1 and 30 characters."
      }
    },
    "lastName": {
      "required": {
        "message": "Last name is required."
      },
      "size": {
        "min": 4,
        "max": 31,
        "message": "Last name must be between 4 and 31 characters."
      }
    },
    "age": {
      "min": {
        "value": 0,
        "message": "Age must be between 0 and 99."
      },
      "max": {
        "value": 99,
        "message": "Age must be between 0 and 99."
      }
    },
    "email": {
      "email": {
        "message": "Must be a valid E-Mail address."
      }
    },
    "password": {
      "pattern": {
        "value": "^.*(?=.{8,})(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).*$",
        "message": "Must be a valid password."
      }
    },
    "url": {
      "url": {
        "message": "Must be a valid URL."
      }
    }
  }
});
}})();
