/*! Auto-generated. This file was generated by Nca.Valdr. */
(function() {
    "use strict";
    angular
        .module("app")
        .config(config);
    config.$inject = ["valdrProvider"];
    function config(valdrProvider) {
        valdrProvider.addConstraints({
  "address": {
    "city": {
      "required": {
        "message": "Ort ist obligatorisch."
      }
    },
    "zipCode": {
      "required": {
        "message": "PLZ ist obligatorisch."
      },
      "size": {
        "min": 4,
        "max": 6,
        "message": "PLZ muss zwischen 4 und 6 Zeichen sein."
      }
    }
  },
  "person": {
    "firstName": {
      "required": {
        "message": "Vorname ist obligatorisch."
      },
      "size": {
        "min": 1,
        "max": 30,
        "message": "Vorname muss zwischen 1 und 30 Zeichen sein."
      }
    },
    "lastName": {
      "required": {
        "message": "Nachname ist obligatorisch."
      },
      "size": {
        "min": 4,
        "max": 31,
        "message": "Nachname muss zwischen 4 und 31 Zeichen sein."
      }
    },
    "age": {
      "min": {
        "value": 0,
        "message": "Age must be between 0 and 99."
      },
      "max": {
        "value": 99,
        "message": "Age must be between 0 and 99."
      }
    },
    "email": {
      "email": {
        "message": "Must be a valid E-Mail address."
      }
    },
    "password": {
      "pattern": {
        "value": "^.*(?=.{8,})(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).*$",
        "message": "Must be a valid password."
      }
    },
    "url": {
      "url": {
        "message": "Must be a valid URL."
      }
    }
  }
});
}})();
